countries_list = [
    "Algeria",
    "Angola",
    "Argentina",
    "Aruba",
    "Australia",
    "Azerbaijan",
    "Bangladesh",
    "Belarus",
    "Bhutan",
    "Bulgaria",
    "Cameroon",
    "China",
    "Colombia",
    "Comoros",
    "Congo (Kinshasa)",
    "Dominican Republic",
    "Egypt",
    "El Salvador",
    "Ethiopia",
    "France",
    "Gabon",
    "India",
    "Indonesia",
    "Iran",
    "Japan",
    "Japan",
    "Lebanon",
    "Madagascar",
    "Mauritius",
    "Montserrat",
    "Netherlands",
    "New Zealand",
    "Norfolk Island",
    "Norway",
    "Pakistan",
    "Philippines",
    "Pitcairn Islands",
    "Russia",
    "Sierra Leone",
    "Singapore",
    "South Africa",
    "South Korea",
    "Sweden",
    "Syria",
    "Taiwan",
    "Thailand",
    "Timor-Leste",
    "United Arab Emirates",
    "United Kingdom",
    "United States",
    "Venezuela",
    "Zambia",
]
