name: Build
on:
  workflow_run:
    workflows: ["Code Quality"]
    types:
      - completed
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
    
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2.1.0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      
      - name: Login to Google Container Registry
        uses: google-github-actions/setup-gcloud@v2.1.0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
            
      - name: Build and push Docker image to GCR
        run: |
          gcloud auth configure-docker --project=${{ secrets.GCP_PROJECT_ID }}
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/sse-main-app:$GITHUB_SHA .
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/sse-main-app:$GITHUB_SHA

  deploy-to-cloud-run:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Set up Google Cloud
        uses: google-github-actions/setup-gcloud@v2.1.0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Authenticate Google Cloud
        uses: google-github-actions/auth@v2.1.0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          
      - name: Confirm Google Cloud Authentication
        run: gcloud auth list

      - name: List Image Tags and Details in GCR
        run: gcloud container images list-tags gcr.io/${{ secrets.GCP_PROJECT_ID }}/sse-main-app

      - name: Set port for Google Cloud Run service
        run: gcloud run services update sse-main-app --port=5000 --platform=managed --region=europe-west2

      - name: Deploy to Google Cloud Run
        run: |
          gcloud run deploy sse-main-app \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/sse-main-app \
            --platform managed \
            --region europe-west2 \
            --port 5000
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
