name: Build
on: [push]
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v1

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2.1.0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      
      - name: Login to Google Container Registry
        uses: google-github-actions/setup-gcloud@v2.1.0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
      
      - name: Echo GITHUB_SHA
        run: |
          echo "GITHUB-SHA: $GITHUB_SHA"
      
      - name: Build and push Docker image to GCR
        run: |
          gcloud auth configure-docker --project=${{ secrets.GCP_PROJECT_ID }}
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/sse-main-app:$GITHUB_SHA .
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/sse-main-app:$GITHUB_SHA

  deploy-to-cloud-run:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Set up Google Cloud
        uses: google-github-actions/setup-gcloud@v2.1.0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Authenticate Google Cloud
        uses: google-github-actions/auth@v2.1.0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Echo GITHUB_SHA
        run: |
          echo "GITHUB-SHA: $GITHUB_SHA"
          echo "gcr.io/${{ secrets.GCP_PROJECT_ID }}/sse-main-app:$GITHUB_SHA"

      - name: Deploy to Google Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2.1.0
        with:
          service: sse-main-app
          image: gcr.io/${{ secrets.GCP_PROJECT_ID }}/sse-main-app:$GITHUB_SHA
          project_id: ${{ secrets.GCP_PROJECT_ID }}
