name: CI/CD Pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  code-quality:
    uses: ./.github/workflows/testing.yml
    secrets: inherit

  testing:
    needs: code-quality
    uses: ./.github/workflows/code-quality.yml
    secrets: inherit
  
  container-setup:
    needs: testing
    uses: ./.github/workflows/container-setup.yml
    secrets: inherit

  deploy-to-staging:
    needs: container-setup
    uses: ./.github/workflows/deploy-to-staging.yml
    secrets: inherit
  
  deploy-to-production:
    needs: deploy-to-staging
    uses: ./.github/workflows/deploy-to-production.yml
    secrets: inherit
    
    
