 name: Container setup

on:
  workflow_call:

jobs:
  container-setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Google Container Registry
        uses: google-github-actions/setup-gcloud@v2.1.0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
      - name: Build and push Docker image to GCR
        run: |
          gcloud auth configure-docker --project=${{ secrets.GCP_PROJECT_ID }}
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/sse-main-app:$GITHUB_SHA .
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/sse-main-app:$GITHUB_SHA
      