name: Deploy to production
on:
  workflow_call:

jobs:
  deploy-to-production:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2.1.0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud
        uses: google-github-actions/setup-gcloud@v2.1.0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
          
      - name: Confirm Google Cloud Authentication
        run: gcloud auth list

      - name: List Image Tags and Details in GCR
        run: gcloud container images list-tags gcr.io/${{ secrets.GCP_PROJECT_ID }}/sse-main-app

      - name: Set port for Google Cloud Run service
        run: gcloud run services update sse-main-app --port=5000 --platform=managed --region=europe-west2

      - name: Deploy to Google Cloud Run
        run: |
          gcloud run deploy sse-main-app \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/sse-main-app \
            --platform managed \
            --region europe-west2 \
            --port 5000
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
