--image gcr.io/${{ secrets.GCP_PROJECT_ID }}/sse-main-app:$GITHUB_SHA \
            --platform managed \
            --region europe-west2 \
            --port 5000 \
            --set-env-vars GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }},GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }},GATEWAY_HOST=${{ secrets.GATEWAY_HOST }},SERVICE_ACCOUNT_JSON=${{ secrets.SERVICE_ACCOUNT_JSON }},FLASK_SECRET_KEY=${{ secrets.FLASK_SECRET_KEY }}