name: Selenium Test

on: 
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        # No need to install selenium here if it's already listed in requirements.txt
        
    - name: Set up Chrome
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: 'latest' # Ensures the latest version of Chrome is used
    - run: chrome --version # This line checks the installed Chrome version, it should be part of a step.
      
    - name: Install ChromeDriver
      uses: nanasess/setup-chromedriver@v2
      with:
        chromedriver-version: 'latest' # Ensures compatibility with the installed Chrome version

    - name: Setup Xvfb
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb libxi6 libgconf-2-4
        sudo Xvfb :99 -ac -screen 0 1280x1024x24 &
        export DISPLAY=:99

    - name: Run Selenium Test
      run: python api/ui_test.py
